site_name: 小狼的实验室
site_url: https://xionglongztz.github.io/
nav:
  - Homepage: index.md
  - DIY:
    - 远古的回响：拆解分析老式微波炉计时器总成: DIY/远古的回响：拆解分析老式微波炉计时器总成.md
  - Thinking:
    - 关于DDRKirby(ISQ)的博客的思考: thinking/关于DDRKirby(ISQ)的博客的思考.md
    - 对不同开源项目的思考：为爱发电真的值得吗: thinking/对不同开源项目的思考：为爱发电真的值得吗.md
    - 个人思想总结报告: thinking/个人思想总结报告.md
  - AI:
    - 关于AI的系统提示词的破解与思考: AI/关于AI的系统提示词的破解与思考.md
    - 人类史上最大的一场阳谋: AI/人类史上最大的一场阳谋.md
  - Other:
    - 图片颜色量化：Chromis设计: other/图片颜色量化：Chromis设计.md
theme:
  name: material # 主题为material
  custom_dir: docs/overrides
  favicon: assets/favicon.png # 自定义favicon
  palette:
    scheme: slate
    primary: custom # 自定义主题色
extra_css:
  - stylesheets/extra.css
